version: '3.3'
services:
  node:
    build:
      context: .
      target: dev
    command: sh -c "yarn && yarn hackmyresume:build && yarn dev:browser-sync"
    ports:
      - 9000:9000
    working_dir: /app
    volumes:
      - .:/app
